name: Talents
version: '1.0'
main: org.twightlight.talents.Talents
depend:
  - packetevents
  - PVPManager
softdepend: [ PlaceholderAPI, BedWars1058 ]
load: POSTWORLD
commands:
  talents:
  skills:
  runes:

